### ISSUE TITLE
question about the 1.2.10.post versions on pypi

### ISSUE THREAD

**Issue by robkorv** [hashberg-io/typing-validation#19]
Hello!

I'm going to try out this library and I noticed several 1.2.10 versions on https://pypi.org/project/typing-validation/#history.
I could not find any reference in the source code about this.

What's the difference between the 1.2.10 version and the 1.2.10.post versions?

![image](https://github.com/hashberg-io/typing-validation/assets/4266355/1ae7129d-7425-44d1-bedd-d196d4fd5bb3)

Which one should I use if I decide to use this library in a production environment?

**Comment by sg495** [comment]
Hi! The `.postX` versions usually have minor fixes (to docs, to minor bugs in test fixtures for older Python versions, etc). I have now released `1.2.11`, which you can use for production.

Note that there's already a `1.2.11.post1`... it fixes a small regression in one of the test fixtures, because I incorrectly refactored an import. The `typing-validation` library code is the same as `1.2.11` 😄
